CarMaintenance/config/routes.rb
Rails.application.routes.draw do
  root "customers#index"
  resources :customers, :fixes, :issues
  get '/customers/:id/done', to: 'customers#done', as: 'done_customer'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

CarMaintenance/app/models/customer.rb
class Customer < ApplicationRecord
  has_many :issues, dependent: :delete_all
  has_many :fixes, through: :issues
end

CarMaintenance/app/models/fix.rb
class Fix < ApplicationRecord
      belongs_to :issue
end

CarMaintenance/app/models/issue.rb
class Issue < ApplicationRecord
      belongs_to :customer
        has_many  :fixes, dependent: :delete_all
end

CarMaintenance/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :card]

  def index
    # @customers = case params[:status]
    #              when "fixed" then Customer.where(fixed: true).order(:id)
    #              when "broken" then Customer.where(fixed: false).order(:id)
    #              else
    #                Customer.all
    #              end
    if params[:search] == nil ||  params[:search] == ""
 if params[:fixed] == "true"
        @customers = Customer.where(fixed: true)
      else
        @customers = Customer.where(fixed: false)
      end
    else
     if params[:fixed] == "true"
        @customers = Customer.where(fixed: true, id: params[:search])
      else
        @customers = Customer.where(fixed: false, id: params[:search])
      end
    end
  end
  
  def show
    @issues = @customer.issues
    @issue = Issue.new
  end

  def edit
  end

  def card
  end

  def update
    customer = Customer.find_by(id: params[:id])
    customer.update(customer_params)
    redirect_to customers_path
  end

  def create
    Customer.create(customer_params)
    redirect_to customers_path
  end

  def new
    @customer = Customer.new
  end

  def done
    customer = Customer.find_by(id: params[:id])
    if params[:return_undone] != "true"
      customer.fixed = true
      customer.fixed_date_time = DateTime.now
    else
      customer.fixed = false
      customer.fixed_date_time = nil
    end
    customer.save
    redirect_to request.referer
  end

  def set_customer
    @customer = Customer.find_by(id: params[:id])
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :mobile, :car_name, :car_plate, :fixed, :fixed_date_time, :entery_date_time)
  end

  def customer_params2
    params.require(:customer).permit(:id)
  end

  # t.string "customer_name"
  # t.string "mobile"
  # t.string "car_name"
  # t.string "car_plate"
  # t.boolean "fixed"
  # t.datetime "fixed_date_time"
  # t.datetime "created_at", null: false
  # t.datetime "updated_at", null:
end

CarMaintenance/app/controllers/fixes_controller.rb
class FixesController < ApplicationController
  def edit
    @fix = Fix.find_by(id: params[:id])
  end

  def update
    fix = Fix.find_by(id: params[:id])
    fix.update(fix_params)
    redirect_to customer_path fix.issue.customer.id
  end

  def create
    Fix.create(fix_params)
    redirect_to request.referer
    # redirect_to customer_path car.customer.id
  end

  def new
    @fix = Fix.new
  end

  def destroy
    fix = Fix.destroy(params[:id])
    redirect_to request.referer
  end

  private

  def fix_params
    if params[:id]
      params.require(:fix).permit(:name, :part_cost, :hand_cost)
    else
      params.require(:fix).permit(:name, :part_cost, :hand_cost, :issue_id)
    end
  end

  # def fix_params_for_update
  #   params.require(:fix).permit(:name, :part_cost, :hand_cost)
  # end

  #  t.string "part_name"
  #     t.integer "part_cost"
  #     t.integer "hand_cost"
  #     t.integer "total_cost"
  #     t.integer "car_issue_id"
  #     t.datetime "created_at", null: false
  #     t.datetime "updated_at", null

end

CarMaintenance/app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def edit
    @issue = Issue.find_by(id: params[:id])
  end

  def update
    issue = Issue.find_by(id: params[:id])
    issue.update(issue_params2)
    redirect_to customer_path issue.customer
  end

  def create
    Issue.create(issue_params)
    redirect_to request.referer
    # rise
    # redirect_to CarEntery_path car.car_entery.id
  end

  def new
    @issue = Issue.new
  end

  def destroy
    Issue.destroy(params[:id])
    redirect_to request.referer
  end

  def index
  end

  private

  def issue_params
    params.require(:issue).permit(:name, :customer_id)
  end

  def issue_params2
    params.require(:issue).permit(:name)
  end

  #     t.string "name"
  #     t.integer "car_entery_id"
  #     t.datetime "created_at", null: false
  #     t.datetime "updated_at"

end

CarMaintenance/app/helpers/car_enteries_helper.rb
module CarEnteriesHelper
end

CarMaintenance/app/helpers/car_fixes_helper.rb
module CarFixesHelper
end

CarMaintenance/app/helpers/car_issues_helper.rb
module CarIssuesHelper
end

CarMaintenance/app/views/customers/_form.html.erb
<%= form_for @customer do |f| %>
<p>
<%= f.label :name %><br>
<%= f.text_field :name %>
</p>
<p>
<%= f.label :mobile %><br>
<%= f.text_field :mobile %>
</p>
<p>
<%= f.label :car_name %><br>
<%= f.text_field :car_name %>
</p>
<p>
<%= f.label :car_plate %><br>
<%= f.text_field :car_plate %>
</p>
<p>
<%= f.label :entery_date_time %><br>
<% if @customer.id.nil? %>
<%= f.datetime_field :entery_date_time, value: DateTime.now.strftime('%Y-%m-%dT%H:%M') %>
<% else %>
<%= f.datetime_field :entery_date_time %>
<% end %>
</p>

<p>
    <%= f.submit %>
</p>
<% end %>

CarMaintenance/app/views/customers/edit.html.erb
<%= render partial: 'form' %>

CarMaintenance/app/views/customers/index.html.erb
 <table class="striped " id="table_id">
        <thead>
          <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Mobile</th>
              <th>Car Name</th>
              <th>Car Plate</th>
              <th>Entery Time</th>
              <th>Action</th>
          </tr>
        </thead>

        <tbody>
          <% @customers.order(:name).each do |cust| %>
          <tr>
            <td><%= link_to cust.id , customer_path(cust) %></td>
            <td><%= link_to cust.name , customer_path(cust) %></td>
            <td> <%=  cust.mobile %> </td>
            <td> <%=  cust.car_name %> </td>
            <td> <%=  cust.car_plate %> </td>
            <td> <%=  distance_of_time_in_words(cust.entery_date_time,DateTime.now) %> </td>
            <td> 
<% if params[:fixed] != "true" %>
            <%=  link_to "Edit", edit_customer_path(cust) %> </td>
<% else %>
  <%= link_to "UnDone It", done_customer_path(cust,:return_undone => "true"),data: { confirm: 'Are you sure?' } %>

            <% end %>
          </tr>
<% end %>
        </tbody>
      </table>

CarMaintenance/app/views/customers/new.html.erb
<%= render partial: "form" %>

CarMaintenance/app/views/customers/show.html.erb
<%if params[:card]=="true" %>
<% print_view=1%>
<% end%>


<div class="hide-in-print">
  <div class="row justify-content-md-cente">
    <% if print_view != 1%>
    <div class="col-md-auto">
    <%= link_to "print card", customer_path(@customer,:card => "true") %>
    </div>
    <% if @customer.fixed != true %>
    <div class="col-md-auto">
    <%= link_to "Set Customer Car To Done", done_customer_path(@customer),data: { confirm: 'Are you sure?' } %>
    </div>
    <% end %>
  <% else %>
    <div class="col-md-auto">
    <%= link_to "Back To Customer", customer_path(@customer) %>
    </div>
  <% end %>
  </div>
  <% grand_total = 0%>
<br>
  <table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark" >
      <tr>
        <th scope="col" >Name</th>
        <th scope="col" >Mobile</th>
        <th scope="col" >Car Name</th>
        <th scope="col" >Car Plate</th>
        <th scope="col" >Entery Time</th>
        <th scope="col" >Fixed</th>
        <th scope="col" >Fix Date</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td> <%=  @customer.name  %></td>
        <td> <%=  @customer.mobile %> </td>
        <td> <%=  @customer.car_name %> </td>
        <td> <%=  @customer.car_plate %> </td>
        <td> <%=  distance_of_time_in_words(@customer.entery_date_time,DateTime.now) %> </td>
        <td> <%=  @customer.fixed %> </td>
        <td> 
            <% if@customer.fixed_date_time %>
            <%=  distance_of_time_in_words(@customer.fixed_date_time,DateTime.now)  %> 
            <% end %>
        </td>
      </tr>
    </tbody>
  </table>

  car issues:
  <% if @issues.length == 0%>
  <br> there are no issues added yet
  <% end %>
  <ol>
    <% @issues.order(:id).each do |issue| %>
    <li>
    <div class="row">
        <div class="col-sm">
          <%= issue.name %>
        </div>
        <% if print_view != 1%>
          <% if @customer.fixed != true %>
          <div class="col-sm">
            <%= link_to 'Edit', edit_issue_path(issue) %> 
          </div>
          <div class="col-sm">
          <%= link_to("Delete", issue_path(issue), method: :delete ,data: { confirm: 'Are you sure?' }) %> <br>
          </div>
          <% end %>
        <% end %>
    </div>
    </li>
<br>
  <table class="table table-striped table-bordered table-sm "  >
    <thead class="thead-dark" >
      <tr>
          <th>Name</th>
          <th>Part Cost</th>
          <th>Hand Cost</th>
          <th>Total</th>
          <% if print_view != 1%>
            <% if @customer.fixed != true %>
            <th>Actions</th>
            <% end %>
          <% end %>
      </tr>
    </thead>
    <tbody>
  <% total = 0%>
  <% issue.fixes.order(:id).each do |fix| %>
      <tr>
        <td> <%=  fix.name  %></td>
        <td> <%=  fix.part_cost.to_s %> </td>
        <td> <%=  fix.hand_cost.to_s %> </td>
          <% total += fix.part_cost+fix.hand_cost %>
        <td> <%=  (fix.part_cost+fix.hand_cost).to_s %> </td>
          <% if print_view != 1 %>
            <% if @customer.fixed != true %>
        <td> 
            <%=  link_to "Edit", edit_fix_path(fix) %>  <%= link_to("Delete", fix_path(fix), method: :delete ,data: { confirm: 'Are you sure?' }) %> 
        </td>
            <% end %>
          <% end %>
            </tr>
  <% end %>
      <tr>
        <td></td>
        <td> </td>
        <td>Total Sum:</td>
        <td><%= total %></td>
        <% grand_total += total %>
        <% if print_view != 1 %>
          <% if @customer.fixed != true %>
        <td> </td>
          <% end %>
        <% end %>
      </tr>
    </tbody>
  </table>
  
  <% @fix = Fix.new %>
  <% @issue_id = issue.id %>
    <% if print_view != 1 %>
      <% if @customer.fixed != true %>

      <%= render partial: 'fixes/form',object: @fix %>
      <% end %>
    <% end %>
  <% end %>
  </ol>
  <% if print_view != 1  %>
    <% if @customer.fixed != true %>
     <%= render partial: 'issues/form',object: @customer_id = @customer.id %>
    <% end %>
  <% end %>
  <br>
  Grand Total: <%= grand_total %>

CarMaintenance/app/views/fixes/_form.html.erb
        <%= form_for @fix  do |f| %>
        <p>
                <div class="form-row">
                        <div class="col-md-3 mb-1">
                                <%= f.label :name, "Fix name: " %>
                                <%= f.text_field :name %>
                        </div>
                        <div class="col-md-3 mb-1">
                                <%= f.label :part_cost %>
                                <% if @fix.id != nil %>
                                <%= f.text_field :part_cost %>
                                <% else %>
                                <%= f.text_field :part_cost, value: 0 %>
                                <% end %>
                        </div>
                        <div class="col-md-3 mb-1">
                                <%= f.label :hand_cost %>
                                <% if @fix.id != nil %>
                                        <%= f.text_field :hand_cost %>
                                <% else %>
                                        <%= f.text_field :hand_cost, value: 0 %>
                                <% end %>
                        </div>
                </div>
                <%= f.submit %>
        </p>
        <%= hidden_field_tag "fix[issue_id]", @issue_id %>
        <% end %>

CarMaintenance/app/views/fixes/edit.html.erb
<%= render partial: 'form' %>

CarMaintenance/app/views/issues/_form.html.erb
<%= form_for @issue do |f| %>
  <div class="form-row">
    <div class="col-md-3 mb-1">
      <%= f.label :name, "issue name: " %>
      <%= f.text_field :name %>
    </div>
    <div class=" col s6">
      <%= f.submit %>
    </div>
  </div>
  <%= hidden_field_tag "issue[customer_id]", @customer_id%>
<% end %>

CarMaintenance/app/views/issues/edit.html.erb
<%= render partial: 'form' %>

CarMaintenance/app/views/issues/index.html.erb
<h1>index</h1>

CarMaintenance/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarMaintenance</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>



<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.18/css/jquery.dataTables.min.css">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" ></script>
        <script src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>

  </head>

  <body>

  <div class="container">
  <div class="row justify-content-md-center">
    <div class="col-md-auto">
  <%= link_to "All Customers Not Done", customers_path(:fixed => false) %>
    </div>
    <div class="col-md-auto">
  <%= link_to "All Customers Done ", customers_path(:fixed => true) %>
    </div>
    <div class="col-md-auto">
  <%= link_to "New Customer", new_customer_path %>
    </div>
  </div>
</div>
     
      

     <br>
     <br>

  <div class="container">
 
    <%= yield %>
     </div>
  
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>